=== folio-org/mod-inn-reach/src/main/resources/swagger.api/schemas/circulation/checkOutResponseDTO.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "Loan",
  "description": "Links the item with the patron and applies certain conditions based on policies",
  "properties": {
    "id": {
      "description": "Unique ID (generated UUID) of the loan",
      "type": "string",
      "format": "UUID"
    },
    "userId": {
      "description": "ID of the patron the item was lent to. Required for open loans, not required for closed loans (for anonymization).",
      "type": "string",
      "format": "UUID"
    },
    "borrower": {
      "description": "Additional information about the borrower of the item, taken from the user referred to by the userId",
      "readonly": true,
      "type": "object",
      "properties": {
        "firstName": {
          "description": "first name of the borrower (read only, defined by the server)",
          "type": "string",
          "readonly": true
        },
        "lastName": {
          "description": "last name of the borrower (read only, defined by the server)",
          "type": "string",
          "readonly": true
        },
        "middleName": {
          "description": "middle name of the borrower (read only, defined by the server)",
          "type": "string",
          "readonly": true
        },
        "barcode": {
          "description": "barcode used to identify the borrower (read only, defined by the server)",
          "type": "string",
          "readonly": true
        }
      },
      "additionalProperties": false
    },
    "proxyUserId": {
      "description": "ID of the user representing a proxy for the patron",
      "type": "string",
      "format": "UUID"
    },
    "itemId": {
      "description": "ID of the item lent to the patron",
      "type": "string",
      "format": "UUID"
    },
    "loanPolicyId": {
      "description": "ID of last policy used in relation to this loan",
      "type": "string",
      "format": "UUID"
    },
    "loanPolicy": {
      "description": "Additional information about the loan policy of the item, taken from the loan loanPolicyId",
      "readonly": true,
      "type": "object",
      "properties": {
        "name": {
          "readonly": true,
          "description": "Name of last policy used in relation to this loan (read only, defined by the server)",
          "type": "string"
        }
      }
    },
    "overdueFinePolicyId": {
      "description": "ID of last overdue fine policy used in relation to this loan",
      "type": "string",
      "format": "UUID"
    },
    "overdueFinePolicy": {
      "description": "Additional information about the overdue fine policy of the item, taken from the loan overdueFinePolicyId",
      "readonly": true,
      "type": "object",
      "properties": {
        "name": {
          "readonly": true,
          "description": "Name of last overdue fine policy used in relation to this loan (read only, defined by the server)",
          "type": "string"
        }
      }
    },
    "lostItemPolicyId": {
      "description": "ID of last lost item policy used in relation to this loan",
      "type": "string",
      "format": "UUID"
    },
    "lostItemPolicy": {
      "description": "Additional information about the lost item policy of the item, taken from the loan lostItemPolicyId",
      "readonly": true,
      "type": "object",
      "properties": {
        "name": {
          "readonly": true,
          "description": "Name of last lost item policy used in relation to this loan (read only, defined by the server)",
          "type": "string"
        }
      }
    },
    "item": {
      "description": "Additional information about the item",
      "type": "object",
      "readonly": true,
      "properties": {
        "id": {
          "description": "ID of the item",
          "type": "string",
          "readonly": true,
          "format": "UUID"
        },
        "title": {
          "description": "The title of the item lent to the patron",
          "type": "string",
          "readonly": true
        },
        "callNumber": {
          "description": "Deprecated call number from the holdings record, use callNumberComponents.callNumber instead",
          "type": "string",
          "readonly": true
        },
        "materialType": {
          "description": "The material type from the item record",
          "type": "object",
          "readonly": true,
          "properties": {
            "name": {
              "description": "Name of the material type",
              "type": "string",
              "readonly": true
            }
          },
          "additionalProperties": false
        },
        "contributors": {
          "description": "Contributors from the instance record",
          "type": "array",
          "readonly": true,
          "items": {
            "type": "object",
            "properties": {
              "name": {
                "description": "Name of the contributor",
                "type": "string",
                "readonly": true
              }
            },
            "additionalProperties": false
          }
        },
        "holdingsRecordId": {
          "description": "The ID of the holdings for the item",
          "type": "string",
          "readonly": true,
          "format": "UUID"
        },
        "instanceId": {
          "description": "The ID of the instance for the item",
          "type": "string",
          "readonly": true,
          "format": "UUID"
        },
        "barcode": {
          "description": "The barcode of the item",
          "type": "string",
          "readonly": true
        },
        "location": {
          "description": "The effective location of the item",
          "type": "object",
          "readonly": true,
          "properties": {
            "name": {
              "description": "The name of the location",
              "type": "string",
              "readonly": true
            }
          }
        },
        "status": {
          "description": "Overall status of the item",
          "type": "object",
          "readonly": true,
          "properties": {
            "name": {
              "description": "Name of the item status",
              "type": "string",
              "readonly": true
            },
            "date": {
              "type": "string",
              "description": "Date time when status was last changed",
              "format": "date-time",
              "readonly": true
            }
          },
          "additionalProperties": false
        },
        "inTransitDestinationServicePointId": {
          "description": "Service point an item is intended to be transited to (should only be present when in transit)",
          "type": "string",
          "readonly": true,
          "format": "UUID"
        },
        "inTransitDestinationServicePoint": {
          "description": "Service point an item is intended to be transited to (should only be present when in transit)",
          "type": "object",
          "readonly": true,
          "properties": {
            "name": {
              "description": "Name of the service point",
              "type": "string",
              "readonly": true
            }
          }
        },
        "enumeration": {
          "description": "Item`s enumeration",
          "type": "string",
          "readonly": true
        },
        "chronology": {
          "description": "Item`s chronology",
          "type": "string",
          "readonly": true
        },
        "volume": {
          "description": "Item`s volume",
          "type": "string",
          "readonly": true
        },
        "callNumberComponents": {
          "description": "Elements of a full call number",
          "readonly": true,
          "$schema": "http://json-schema.org/draft-04/schema#",
          "type": "object",
          "properties": {
            "callNumber": {
              "type": "string",
              "description": "Call number for item",
              "readonly": true
            },
            "prefix": {
              "description": "Call number prefix for item",
              "type": "string",
              "readonly": true
            },
            "suffix": {
              "description": "Call number suffix for item",
              "type": "string",
              "readonly": true
            }
          }
        }
      },
      "additionalProperties": false
    },
    "itemEffectiveLocationIdAtCheckOut": {
      "description": "The effective location, at the time of checkout, of the item loaned to the patron.",
      "type": "string",
      "format": "UUID"
    },
    "status": {
      "description": "Overall status of the loan",
      "type": "object",
      "properties": {
        "name": {
          "description": "Name of the status (currently can be any value, values commonly used are Open and Closed)",
          "type": "string"
        }
      }
    },
    "loanDate": {
      "description": "Date and time when the loan began",
      "type": "string",
      "format": "date-time"
    },
    "dueDate": {
      "description": "Date and time when the item is due to be returned",
      "type": "string",
      "format": "date-time"
    },
    "returnDate": {
      "description": "Date and time when the item was returned",
      "type": "string",
      "format": "date-time"
    },
    "systemReturnDate": {
      "description": "Date and time when return was processed",
      "type": "string",
      "format": "date-time"
    },
    "action": {
      "description": "Last action performed on a loan (currently can be any value, values commonly used are checkedout and checkedin)",
      "type": "string"
    },
    "renewalCount": {
      "description": "Count of how many times a loan has been renewed (incremented by the client)",
      "type": "integer",
      "minimum": 0
    },
    "checkoutServicePointId": {
      "description": "ID of the Service Point where the last checkout occured",
      "type": "string",
      "format": "UUID"
    },
    "checkinServicePointId": {
      "description": "ID of the Service Point where the last checkin occured",
      "type": "string",
      "format": "UUID"
    },
    "checkoutServicePoint": {
      "description": "The Service Point where the last checkout occurred",
      "type": "object",
      "readonly": true,
      "properties": {
        "name": {
          "description": "The unique name of the service point",
          "type": "string",
          "readonly": true
        },
        "code": {
          "description": "The short code for the service point",
          "type": "string",
          "readonly": true
        },
        "discoveryDisplayName": {
          "description": "The human readable name",
          "type": "string",
          "readonly": true
        },
        "shelvingLagTime": {
          "description": "The time to shelving",
          "type": "integer",
          "readonly": true
        },
        "pickupLocation": {
          "description": "Is this a pickup location",
          "type": "boolean",
          "readonly": true
        }
      }
    },
    "checkinServicePoint": {
      "description": "The Service Point where the last checkout occurred",
      "type": "object",
      "readonly": true,
      "properties": {
        "name": {
          "description": "Name of the service point",
          "type": "string",
          "readonly": true
        },
        "code": {
          "description": "The short code for the service point",
          "type": "string",
          "readonly": true
        },
        "discoveryDisplayName": {
          "description": "The human readable name",
          "type": "string",
          "readonly": true
        },
        "shelvingLagTime": {
          "description": "The time to shelving",
          "type": "integer",
          "readonly": true
        },
        "pickupLocation": {
          "description": "Is this a pickup location",
          "type": "boolean",
          "readonly": true
        }
      }
    },
    "patronGroupAtCheckout": {
      "description": "Patron Group at checkout",
      "type": "object",
      "properties": {
        "id": {
          "description": "Unique ID (generated UUID) of the patron group",
          "type": "string",
          "readonly": true,
          "format": "UUID"
        },
        "name": {
          "description": "Patron group name",
          "type": "string",
          "readonly": true
        }
      },
      "additionalProperties": false
    },
    "feesAndFines": {
      "description": "Fees and fines associated with loans",
      "type": "object",
      "properties": {
        "amountRemainingToPay": {
          "type": "number",
          "description": "Total remaining amount due on fees and fines for the loan (read only, defined by the server)",
          "readonly": true
        }
      },
      "additionalProperties": false
    },
    "declaredLostDate": {
      "description": "Date and time the item was declared lost during this loan",
      "type": "string",
      "format": "date-time"
    },
    "metadata": {
      "description": "Metadata about creation and changes to loan, provided by the server (client should not provide)",
      "type": "object",
      "$schema": "http://json-schema.org/draft-04/schema#",
      "title": "Metadata Schema",
      "properties": {
        "createdDate": {
          "description": "Date and time when the record was created",
          "type": "string",
          "format": "date-time"
        },
        "createdByUserId": {
          "description": "ID of the user who created the record (when available)",
          "type": "string",
          "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
        },
        "createdByUsername": {
          "description": "Username of the user who created the record (when available)",
          "type": "string"
        },
        "updatedDate": {
          "description": "Date and time when the record was last updated",
          "type": "string",
          "format": "date-time"
        },
        "updatedByUserId": {
          "description": "ID of the user who last updated the record (when available)",
          "type": "string",
          "pattern": "^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$"
        },
        "updatedByUsername": {
          "description": "Username of the user who last updated the record (when available)",
          "type": "string"
        }
      },
      "additionalProperties": false,
      "required": [
        "createdDate"
      ]
    }
  },
  "required": [
    "itemId",
    "loanDate",
    "action"
  ]
}

=== folio-org/mod-inn-reach/src/test/resources/wm/__files/circulation/checkout-response.json
{
  "id": "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  "userId": "a7853dda-520b-4f7a-a1fb-9383665ea770",
  "itemId": "4def31b0-2b60-4531-ad44-7eab60fa5428",
  "status": {
    "name": "Open"
  },
  "loanDate": "2025-01-01T00:00:00.000Z",
  "dueDate": "2025-02-01T00:00:00.000Z",
  "action": "checkedout",
  "item": {
    "id": "4def31b0-2b60-4531-ad44-7eab60fa5428",
    "barcode": "DEF-def-5678",
    "callNumber": "CN-001"
  }
}

=== folio-org/mod-inn-reach/src/test/resources/wm/__files/circulation/open-loan-response.json
{
  "id": "fd5109c7-8934-4294-9504-c1a4a4f07c96",
  "userId": "4154a604-4d5a-4d8e-9160-057fc7b6e6b8",
  "itemId": "9a326225-6530-41cc-9399-a61987bfab3c",
  "status": {
    "name": "Open"
  },
  "loanDate": "2025-01-01T00:00:00.000Z",
  "dueDate": "2025-02-01T00:00:00.000Z",
  "action": "checkedout"
}

=== folio-org/mod-inn-reach/src/test/resources/wm/__files/circulation/item-hold-open-loan-response.json
{
  "id": "06e820e3-71a0-455e-8c73-3963aea677d4",
  "userId": "a7853dda-520b-4f7a-a1fb-9383665ea770",
  "itemId": "4def31b0-2b60-4531-ad44-7eab60fa5428",
  "status": {
    "name": "Open"
  },
  "loanDate": "2025-01-01T00:00:00.000Z",
  "dueDate": "2025-02-01T00:00:00.000Z",
  "action": "checkedout"
}
